module.exports = {
  products: [
    {
      _id: "1",
      name: "Drinking Flask",
      category: "Shirts",
      image: "/images/flask_black.PNG",
      price: 149,
      material: "Metal",
      size: "a",
      rating: 5,
      reviews: 0,
      numInStock: 99,
    },
    {
      _id: "2",
      name: "Black Jumper",
      category: "Hoodie",
      image: "/images/jumper_black.PNG",
      price: 299,
      material: "Cotton",
      size: "L",
      rating: 5,
      reviews: 0,
      numInStock: 99,
    },
    {
      _id: "3",
      name: "White Jumper",
      category: "Hoodie",
      image: "/images/jumper_white.PNG",
      price: 299,
      material: "cotton",
      size: "L",
      rating: 5,
      reviews: 0,
      numInStock: 99,
    },
    {
      _id: "4",
      name: "White Tee",
      category: "Shirts",
      image: "/images/tee_white.PNG",
      price: 199,
      material: "cotton",
      size: "L",
      rating: 5,
      reviews: 0,
      numInStock: 99,
    },
    {
      _id: "5",
      name: "Tee White",
      category: "Shirts",
      image: "/images/tee_white_back.PNG",
      price: 199,
      material: "Cotton",
      size: "L",
      rating: 5,
      reviews: 0,
      numInStock: 99,
    },
  ],
};
